#Database settings
[development]
db.host = "localhost"
db.port = "port"
db.user = "user"
db.password = "password"
db.database = "database_name"

[production]
db.host = ""
db.port = ""
db.user = ""
db.password = ""
db.database = ""